export const COLORS: Record<string, string> = {
  fire: '#ffa756',
  grass: '#8bbe8a',
  electric: '#f2cb55',
  water: '#58abf6',
  ground: '#f78551',
  rock: '#d4c294',
  fairy: '#eba8c3',
  poison: '#9f6e97',
  bug: '#8bd674',
  dragon: '#e16776',
  psychic: '#a552cc',
  flying: '#748fc9',
  fighting: '#eb4971',
  normal: '#b9b8d3',
  ghost: '#8571be',
  ice: '#61cec0',
  dark: '#705746',
  steel: '#b7b7ce',
};

export const POKEMON_TYPES = [
  'normal',
  'fire',
  'water',
  'electric',
  'grass',
  'ice',
  'fighting',
  'poison',
  'ground',
  'flying',
  'psychic',
  'bug',
  'rock',
  'ghost',
  'dragon',
  'dark',
  'steel',
  'fairy',
];
